topic_camera: "/dope/webcam/image_raw"
topic_camera_info: "/dope/webcam/camera_info"
topic_publishing: "dope"
input_is_rectified: True   # Whether the input image is rectified (strongly suggested!)
downscale_height: 500      # if the input image is larger than this, scale it down to this pixel height

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    # "tomatosauce": "package://dope/weights/TomatoSauce.pth",
    "ViroBeerOpener": "package://dope/weights/viro_beeropener_30_old.pth",
    "ViroPen": "package://dope/weights/viro_pen_33_old.pth",
    "ViroUSB": "package://dope/weights/viro_usb_21_old.pth",
    "ViroPeppermint": "package://dope/weights/viro_peppermint_15_old.pth",

}

# Cuboid dimension in cm x,y,z
dimensions: {
    # "tomatosauce": [8.2847003936767578, 7.0198001861572266, 6.6469998359680176],
    "ViroBeerOpener": [8.2208003997802734, 0.5, 6.6668000221252441],
    "ViroPen": [1.0989999771118164, 1.485200047492981, 13.399999618530273],
    "ViroUSB": [0.44999998807907104, 1.2250000238418579, 4.0999999046325684],
    "ViroPeppermint": [7.5999999046325684, 1.8966000080108643, 1.8983000516891479],
}

class_ids: {
    # "tomatosauce": 8,
    "ViroBeerOpener": 1,
    "ViroPen": 2,
    "ViroUSB": 3,
    "ViroPeppermint": 4,
}

draw_colors: {
    # "tomatosauce": [0, 156, 30],
    "ViroBeerOpener": [255, 0, 0],
    "ViroPen": [0, 255, 0],
    "ViroUSB": [127, 127, 0],
    "ViroPeppermint": [127, 0, 127],
}

# optional: provide a transform that is applied to the pose returned by DOPE
model_transforms: {
#    "cracker": [[ 0,  0,  1,  0],
#                [ 0, -1,  0,  0],
#                [ 1,  0,  0,  0],
#                [ 0,  0,  0,  1]]
}

# optional: if you provide a mesh of the object here, a mesh marker will be
# published for visualization in RViz
meshes: {
    "tomatosauce": "package://triple_s_util/meshes/tomato_soup/textured.obj",
    "ViroBeerOpener": "package://triple_s_util/meshes/beer_opener/beer_opener.stl",
    "ViroPen": "package://triple_s_util/meshes/pen/pen_viro.stl",
    "ViroUSB": "package://triple_s_util/meshes/usb_stick/usb_viro.stl",
    "ViroPeppermint": "package://triple_s_util/meshes/peppermint/peppermint.stl",
}

# optional: If the specified meshes are not in meters, provide a scale here (e.g. if the mesh is in centimeters, scale should be 0.01). default scale: 1.0.
mesh_scales: {
    "TomatoSauce": 0.01,
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
